abbr -a -- b brew
abbr -a -- bi 'brew install'
abbr -a -- bs 'brew search'
abbr -a -- bui 'brew uninstall'
abbr -a -- cdr 'cd (ghq list --full-path |peco)'
abbr -a -- clip pbcopy
abbr -a -- cnf config
abbr -a -- d docker
abbr -a -- dco docker-compose
abbr -a -- dcu 'docker-compose up'
abbr -a -- g git
abbr -a -- gbr 'git branch'
abbr -a -- gcam 'git commit --amend -m'
abbr -a -- gcl 'git clone'
abbr -a -- gclean 'git clean -df'
abbr -a -- gcln 'git clone'
abbr -a -- gcm 'git commit -m'
abbr -a -- gco 'git checkout'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- ghg 'ghq get'
abbr -a -- ghl 'ghq list'
abbr -a -- ghr 'ghq root --all'
abbr -a -- glg 'git log'
abbr -a -- gp 'git pull'
abbr -a -- gpl 'git pull'
abbr -a -- gps 'git push origin'
abbr -a -- gra 'git remote add origin'
abbr -a -- grh 'git reset --hard HEAD^'
abbr -a -- gs 'git status'
abbr -a -- gsp 'git stash pop'
abbr -a -- gst 'git stash'
abbr -a -- gsub 'git submodule'
abbr -a -- gsw 'git switch'
abbr -a -- la 'ls -a'
abbr -a -- ll 'ls -l'
abbr -a -- lla 'ls -la'
abbr -a -- pgr 'pipenv graph'
abbr -a -- pinst 'pipenv install'
abbr -a -- prm 'pipenv --rm'
abbr -a -- prun 'pipenv run'
abbr -a -- pshell 'pipenv shell'
abbr -a -- punst 'pipenv uninstall'
abbr -a -- py python
abbr -a -- r 'rm -rf'
abbr -a -- ga 'git add'
abbr -a -- ga. 'git add .'