abbr -a -U -- b brew
abbr -a -U -- bi 'brew install'
abbr -a -U -- bs 'brew search'
abbr -a -U -- bui 'brew uninstall'
abbr -a -U -- cdr 'cd (ghq list --full-path |peco)'
abbr -a -U -- clip pbcopy
abbr -a -U -- d docker
abbr -a -U -- dco docker-compose
abbr -a -U -- dcu 'docker-compose up'
abbr -a -U -- g git
abbr -a -U -- gbr 'git branch'
abbr -a -U -- gcam 'git commit --amend -m'
abbr -a -U -- gcl 'git clone'
abbr -a -U -- gclean 'git clean -df'
abbr -a -U -- gcln 'git clone'
abbr -a -U -- gcm 'git commit -m'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gcp 'git cherry-pick'
abbr -a -U -- ghg 'ghq get'
abbr -a -U -- ghl 'ghq list'
abbr -a -U -- ghr 'ghq root --all'
abbr -a -U -- glg 'git log'
abbr -a -U -- gp 'git pull'
abbr -a -U -- gpl 'git pull'
abbr -a -U -- gps 'git push origin'
abbr -a -U -- gra 'git remote add origin'
abbr -a -U -- grh 'git reset --hard HEAD^'
abbr -a -U -- gs 'git status'
abbr -a -U -- gsp 'git stash pop'
abbr -a -U -- gst 'git stash'
abbr -a -U -- gsub 'git submodule'
abbr -a -U -- gsw 'git switch'
abbr -a -U -- la 'ls -a'
abbr -a -U -- ll 'ls -l'
abbr -a -U -- lla 'ls -la'
abbr -a -U -- pgr 'pipenv graph'
abbr -a -U -- pinst 'pipenv install'
abbr -a -U -- prm 'pipenv --rm'
abbr -a -U -- prun 'pipenv run'
abbr -a -U -- pshell 'pipenv shell'
abbr -a -U -- punst 'pipenv uninstall'
abbr -a -U -- py python
abbr -a -U -- r 'rm -rf'
