name: dotfiles
on: push
jobs:
  on-ubuntu-2004:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: apt update && apt install -y make sudo
    - name: build
      run: make build 