name: dotfiles
on: push
jobs:
  on-ubuntu-2004:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: sudo apt update && sudo apt install -y make
      - name: fish
        run: make fish
  on-ubuntu-2204:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: sudo apt update && sudo apt install -y make
      - name: fish
        run: make fish
  on-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git make
      - name: setup
        run: pacman -Su && make --version
      - name: choco
        run: make choco
  on-mac:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: make --version
      - name: fish
        run: make fish
