name: dotfiles
on: push
jobs:
  on-ubuntu-2004:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: sudo apt update && sudo apt install -y make
    - name: build
      run: make
  on-ubuntu-2204:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: sudo apt update && sudo apt install -y make
    - name: build
      run: make
  on-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup
      shell: bash
      run: update-core && pacman -Su && pacman -S make
